### ISSUE TITLE
Available on NPM

### ISSUE THREAD

**Issue by jrasm91** [smart-on-fhir/health-cards-dev-tools#140]
Is there any reason why this package is not available on [npm](https://www.npmjs.com/)?

IMO, it seems like it would be significantly easier to use (install, update, track, etc.), if it was installable via a package manager. 

Also, you could take advantage of [npx](https://www.npmjs.com/package/npx) for the `CLI` use cases and execute it via something like the following:

```
npx health-cards-validator --path data.smart-health-card --type healthcard
```

**Comment by jmandel** [comment]
I think it'd be good to publish to NPM, but do keep in mind that currently you can still use via CLI from github, e.g. to install based on the current default branch:

     npm install github:smart-on-fhir/health-cards-validation-SDK

Or a specific release:

    npm install github:smart-on-fhir/health-cards-validation-SDK#v1.0.0-4

**Comment by jmandel** [comment]
(I think we'd need to configure package.json differently for this project to work with npx -- whether via github URLs or via NPM package registry. Might need to set up default scripts / commands to support this, with ts-node? I'm not sure what's required, but npx right now suggests it "can't find" the "executable".)

**Comment by jrasm91** [comment]
I opened a PR, which makes `shc-validator` available as a command (#141) and then updated the docs to make some things a bit clearer. For me at least, it was a bit confusing figuring out how to use the tool. I'm open to feedback and happy to make any changes to the PR (or split it up). Let me know.

**Comment by christianpaquin** [comment]
> Is there any reason why this package is not available on [npm](https://www.npmjs.com/)?

Originally, the SDK (which in retrospect isn't the best name, because it's not a SDK to develop software, but a tool to validate other implementations) was meant as an end-user tool, not to be incorporated into other apps through `npm`. We were thinking about reducing its footprint with common, reusable code and make that a npm package; this hasn't materialized and we've since added skd-ish functionality (such as a callable API). It makes sense now to revisit the npm distribution.

Thanks for the PR; @ljoy913 has been working with the API and the related portals (and also looked at npm packaging before), so I'll let him review to make sure your approach is compatible with the roadmap.

**Comment by jrasm91** [comment]
I need to validate a smart health card in another project and have started to write my own validator logic. I decode the JWS, inflate the payload, resolved the issuer's public key, check the signature, parse out the FHIR bundle, etc. It's not trivial, and I have run into a few gotchas. Personally, I think the QRCode translation between `numeric` and `ut8` is particularly confusing. 

IMO, I think it makes sense for there to be a reusable `node` / `npm` package that _correctly_ implements all of those features. It would make it quite a bit easier for other projects that want to adopt and implement smart health card functionality (ie - I'd rather contribute to this project than write my own validator from scratch and I'm sure a lot of people just want a plug and play implementation of the spec, rather than having to code it themselves).

**Comment by christianpaquin** [comment]
Yes, having libraries/package for implementing validation of SMART Health Cards would be valuable (for node/npm and other languages), but that's not something we set out to do since we don't implement a validation app; our goal was always to create a implementation validation tool, to insure conformance with the spec. Our code contains more checks and validations than needed, with extra on-failure steps to figure out _how_ a failure occurs to give feedback to an implementer. This being said, someone could take our code and extract the minimum functionality to create such a package.

**Comment by shahanajoy** [comment]
Hi ,
How to implement health-cards-validation-SDK in angular9 Project

**Comment by ljoy913** [comment]
> Hi ,
> How to implement health-cards-validation-SDK in angular9 Project

The __health-cards-validation-SDK__ was originally designed as a command-line tool to validate SMART Health Cards.  
It does have an exposed API to allow programmatic use, however it cannot currently be used standalone in a client.

You could create a server that performs the validation calls - and have your Angular client make calls to the server for its validation.

**Comment by shahanajoy** [comment]
Thank you for the response.
How to validate QR image getting as  input from client side,instead of command-line

**Comment by jmandel** [comment]
Closing this as a stale issue. The tool is available to install through NPM using a GitHub based dependency.
